### ISSUE TITLE
How to open the .mat shared by you in MagicDNA?

### ISSUE THREAD

**Issue by RodenLuo** [sulcgroup/nanobase#1]
Hi, I found the airplane design structure here: https://nanobase.org/structure/70. After downloading its .mat "MagicDNA design file", I find I cannot load it into MagicDNA. It says unable to read MAT-file. I also wonder how did you generate the preview image below. Thanks. 

![image](https://user-images.githubusercontent.com/8460424/149948047-fff8ce65-b669-414d-b658-fcb025a37929.png)

![image](https://user-images.githubusercontent.com/8460424/149948106-7ce0fa7f-f22a-4b38-a518-0d7188400f24.png)

![image_All4Scaf-2](https://user-images.githubusercontent.com/8460424/149948242-96174d21-bcae-4de3-b1e6-a28b75e17205.png)

**Comment by ErikPoppleton** [comment]
Hi Roden,

You're right that the MagicDNA GitHub is a better place to ask this question.  Maybe try emailing Chao-Min if you don't get a response on GitHub soon?

Best,

Erik
